examples/2d_with_coarsening/2d_with_coarsening.i
Just had to rename some parameters.
Closes #7
=> fix coarsening example

examples/2d_with_coarsening/2d_with_coarsening.i, examples/2d_with_coarsening/plot_num_elements.py
Added a nice little python/matplotlib script to show the results
closes #11
=> added NumElems PPS to coarsening example, added python script

include/kernels/MaterialDiffusion.h, src/kernels/MaterialDiffusion.C
=> made MaterialDiffusion kernel simpler

examples/2d_with_sink/2d_with_sink.i, examples/2d_with_sink/plot_concentration.py, include/kernels/MaterialSinkKernel.h, src/base/PrariedogApp.C, src/kernels/MaterialSinkKernel.C
Added MaterialSinkKernel, which inherits from Reaction
Added an example problem with lots of non-default parameters
Added a python/matplotlib script to plot output and "analytic" solution
closes #13
=> added sink kernel, example, plotting script

examples/2d_with_sink/plot_concentration.py, tests/userobjects/circle_average_material_property/circle_average_material_property.i, tests/userobjects/circle_average_material_property/gold/circle_average_material_property_out.csv
D=1+x, so an average at x=0.5 gives 1.5
closes #18
=> use spatially varying property in test for CircleAverageMaterialProperty

Makefile, src/base/PrariedogApp.C, unit/Makefile
=> compile without modules

tests/userobjects/random_point/tests
For now, just disable threading in the test.
refs #27
=> disable threads on test for RandomPointUserObject, refs #27

include/kernels/MaterialDiffusion.h, src/kernels/MaterialDiffusion.C, tests/userobjects/circle_average_material_property/circle_average_material_property.i, tests/userobjects/circle_average_material_property/points_from_inserter.i
=> Property name in MaterialDiffusion

examples/2d_sigma_ratio_adaptivity/2d_sigma_ratio_adaptivity.i, examples/2d_sigma_ratio_adaptivity/plot_concentration.py, examples/2d_sigma_ratio_adaptivity/plot_num_elements.py, examples/2d_with_sink/2d_with_sink.i, examples/2d_with_sink/plot_concentration.py
Also fixed up some other examples due to #38 
Closes #39
=> Example for sigma element size ratio adaptivity

src/userobjects/GaussianUserObject.C
=> pretty up normalization constant in GaussianUserObject

include/markers/EventMarker.h, include/userobjects/GaussianUserObject.h, src/markers/EventMarker.C, src/userobjects/CircleMaxOriginalElementSize.C
=> no more compiler warnings in debug mode for now

include/dirackernels/DiracSinkMapKernel.h, src/dirackernels/DiracSinkMapKernel.C
=> Adds Jacobian calculation in DiracSinkMapKernel

include/kernels/MaterialDiffusion.h, src/dirackernels/DiracSinkMapKernel.C, src/kernels/MaterialDiffusion.C, src/kernels/MaterialSinkKernel.C, src/kernels/SinkMapKernel.C, tests/dirackernels/dirac_sink_map_kernel.i, tests/dirackernels/dirac_sink_map_kernel_error.i, tests/kernels/material_sink_kernel/material_sink_kernel.i, tests/kernels/sink_map_kernel/sink_map_kernel.i, tests/markers/event_marker_sigma_coarsening_near_refined_sink.i
=> kernels take property names as parameters

examples/2d_sigma_ratio_adaptivity/2d_sigma_ratio_adaptivity.i, examples/2d_sink_map_with_refinement/2d_sink_map_with_refinement.i, examples/2d_with_sink/2d_with_sink.i
also lowered the sigma/element_size ratio for an example to make it run more quickly
closes #54
=> update examples with material names

examples/2d_dirac_sinks/2d_dirac_sinks.i, examples/2d_dirac_sinks/plot_concentration.py, examples/2d_dirac_sinks/plot_num_elements.py
=> added dirac sink example

problems/timestep_sensitivity/gaussian_diffusion/1d_gaussian_diffusion.i, problems/timestep_sensitivity/gaussian_diffusion/run.py, problems/timestep_sensitivity/uniform_IC/1d_uniform_IC.i, problems/timestep_sensitivity/uniform_IC/run.py
They are in the "problems" directory
ref #60
=> adding some timestep sensitivity studies

include/auxkernels/MaterialSinkRateAux.h, include/auxkernels/SinkMapRateAux.h, src/auxkernels/MaterialSinkRateAux.C, src/auxkernels/SinkMapRateAux.C
=> change input variable name in Rate AuxKernels

problems/timestep_sensitivity/gaussian_diffusion/run.py
In the gaussian diffusion timestep study, use a very small time step as the "apparent" target value
also tweak gaussian parameters
ref #60
=> update gaussian diffusion timestep sensitivity script

src/userobjects/EventInserter.C, tests/userobjects/event_inserter/event_inserter_test_event_location_error.i, tests/userobjects/event_inserter/event_inserter_test_event_time_error.i, tests/userobjects/event_inserter/tests
=> Fix for EventInserter test event logic

src/userobjects/CircleAverageMaterialProperty.C, src/userobjects/CircleMaxOriginalElementSize.C, src/userobjects/EventInserter.C, src/userobjects/SinkMapUserObject.C
=> fix error macros to use new moose functions

problems/test_recovery_and_parallel/test_recover_and_parallel.sh
=> fixed typo in recovery script

problems/test_recovery_and_parallel/test_recover_and_parallel.sh
=> print out failed tests after recovery script

src/base/PrariedogApp.C, src/base/PrariedogApp.C.module
=> remove legacy behavior

problems/test_recovery_and_parallel/test_recover_and_parallel.sh, src/kernels/EventInserterSource.C, src/userobjects/EventInserterBase.C
=> remove 'cascade' nomenclature throughout

tests/markers/event_marker.i, tests/markers/event_marker_coarsening.i, tests/markers/event_marker_coarsening_conflict.i, tests/markers/event_marker_coarsening_with_uniform_refine.i, tests/markers/event_marker_denser_mesh_near_sink.i, tests/markers/event_marker_initial_adaptivity.i, tests/markers/event_marker_periodic.i, tests/markers/event_marker_sigma_coarsening.i, tests/markers/event_marker_sigma_coarsening_near_refined_sink.i, tests/markers/event_marker_sigma_ratio_coarsening.i, tests/markers/event_marker_sigma_ratio_refinement.i, tests/markers/random_circle_marker.i, tests/markers/random_circle_marker_initial.i, tests/markers/sink_marker.i, tests/markers/sink_marker_3d.i, tests/markers/sink_marker_inside.i, tests/markers/sink_marker_sigma_ratio_refinement.i
Cleaned up a bunch of extraneous junk in marker tests
closes #150
=> clean up marker tests

examples/2d_dirac_sinks/2d_dirac_sinks.i
=> added volume postprocessor to 2d dirac example

include/auxkernels/CoupledSinkRateAux.h, include/auxkernels/ElementHLevel.h, include/auxkernels/SinkMapAux.h, include/auxkernels/SinkMapRateAux.h, include/functions/GaussianFunction.h, include/markers/EventMarker.h, include/markers/RandomCircleMarker.h, include/postprocessors/CircleMaxOriginalElementSizePPS.h, include/postprocessors/NumPastEvents.h, include/timesteppers/EventTimeStepper.h, include/userobjects/GaussianUserObject.h, include/userobjects/RandomPointUserObject.h, src/functions/GaussianFunction.C, src/postprocessors/CircleMaxOriginalElementSizePPS.C, src/postprocessors/NumPastEvents.C, src/timesteppers/EventTimeStepper.C, src/userobjects/GaussianUserObject.C
Remove all those destructors that got in there blindly copying and pasting from other objects.
closes #148
=> Remove destructors 

problems/mesh_adaptivity_timing/2d_sink_map_with_refinement.i, problems/mesh_adaptivity_timing/3d_sink_map_with_refinement.i, problems/mesh_adaptivity_timing/make_timing_data.py
Based on example 5 input files, with some parameters tweaked.
closes #167
=> adds the mesh adaptivity benchmark problem

problems/mesh_adaptivity_timing/make_timing_data.py
Run fewer events (20 -> 10) but do another bigger mesh size (200x200).
Closes #169
=> tweak mesh adaptivity problem

src/main.C
=> apply Cody's patch to use smart pointers

src/userobjects/CircleAverageMaterialPropertyBase.C, src/userobjects/CircleMaxOriginalElementSize.C, src/userobjects/EventInserterBase.C, src/userobjects/SinkMapUserObject.C
=> Update to ExecFlagEnum

src/markers/RandomCircleMarker.C
If we could get this merged quickly, that would be fantastic
=> Update to current libmesh apis
